# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: test

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 180
  FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10
  
jobs:
  test:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test