# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: test

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Set Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.2.app
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: swift test